/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaJVM_JNITest_JNIsum */

#ifndef _Included_JavaJVM_JNITest_JNIsum
#define _Included_JavaJVM_JNITest_JNIsum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaJVM_JNITest_JNIsum
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaJVM_JNITest_JNIsum_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
